name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prep
      run: sudo apt-get update && apt-get install -y  cmake libclang-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --release --all --verbose
